// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: helloworld/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Helloworld_CreateHelloworld_FullMethodName = "/api.helloworld.Helloworld/CreateHelloworld"
	Helloworld_UpdateHelloworld_FullMethodName = "/api.helloworld.Helloworld/UpdateHelloworld"
	Helloworld_DeleteHelloworld_FullMethodName = "/api.helloworld.Helloworld/DeleteHelloworld"
	Helloworld_GetHelloworld_FullMethodName    = "/api.helloworld.Helloworld/GetHelloworld"
	Helloworld_ListHelloworld_FullMethodName   = "/api.helloworld.Helloworld/ListHelloworld"
)

// HelloworldClient is the client API for Helloworld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloworldClient interface {
	CreateHelloworld(ctx context.Context, in *CreateHelloworldRequest, opts ...grpc.CallOption) (*CreateHelloworldReply, error)
	UpdateHelloworld(ctx context.Context, in *UpdateHelloworldRequest, opts ...grpc.CallOption) (*UpdateHelloworldReply, error)
	DeleteHelloworld(ctx context.Context, in *DeleteHelloworldRequest, opts ...grpc.CallOption) (*DeleteHelloworldReply, error)
	GetHelloworld(ctx context.Context, in *GetHelloworldRequest, opts ...grpc.CallOption) (*GetHelloworldReply, error)
	ListHelloworld(ctx context.Context, in *ListHelloworldRequest, opts ...grpc.CallOption) (*ListHelloworldReply, error)
}

type helloworldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloworldClient(cc grpc.ClientConnInterface) HelloworldClient {
	return &helloworldClient{cc}
}

func (c *helloworldClient) CreateHelloworld(ctx context.Context, in *CreateHelloworldRequest, opts ...grpc.CallOption) (*CreateHelloworldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHelloworldReply)
	err := c.cc.Invoke(ctx, Helloworld_CreateHelloworld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) UpdateHelloworld(ctx context.Context, in *UpdateHelloworldRequest, opts ...grpc.CallOption) (*UpdateHelloworldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHelloworldReply)
	err := c.cc.Invoke(ctx, Helloworld_UpdateHelloworld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) DeleteHelloworld(ctx context.Context, in *DeleteHelloworldRequest, opts ...grpc.CallOption) (*DeleteHelloworldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHelloworldReply)
	err := c.cc.Invoke(ctx, Helloworld_DeleteHelloworld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) GetHelloworld(ctx context.Context, in *GetHelloworldRequest, opts ...grpc.CallOption) (*GetHelloworldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHelloworldReply)
	err := c.cc.Invoke(ctx, Helloworld_GetHelloworld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) ListHelloworld(ctx context.Context, in *ListHelloworldRequest, opts ...grpc.CallOption) (*ListHelloworldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHelloworldReply)
	err := c.cc.Invoke(ctx, Helloworld_ListHelloworld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloworldServer is the server API for Helloworld service.
// All implementations must embed UnimplementedHelloworldServer
// for forward compatibility.
type HelloworldServer interface {
	CreateHelloworld(context.Context, *CreateHelloworldRequest) (*CreateHelloworldReply, error)
	UpdateHelloworld(context.Context, *UpdateHelloworldRequest) (*UpdateHelloworldReply, error)
	DeleteHelloworld(context.Context, *DeleteHelloworldRequest) (*DeleteHelloworldReply, error)
	GetHelloworld(context.Context, *GetHelloworldRequest) (*GetHelloworldReply, error)
	ListHelloworld(context.Context, *ListHelloworldRequest) (*ListHelloworldReply, error)
	mustEmbedUnimplementedHelloworldServer()
}

// UnimplementedHelloworldServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloworldServer struct{}

func (UnimplementedHelloworldServer) CreateHelloworld(context.Context, *CreateHelloworldRequest) (*CreateHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHelloworld not implemented")
}
func (UnimplementedHelloworldServer) UpdateHelloworld(context.Context, *UpdateHelloworldRequest) (*UpdateHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHelloworld not implemented")
}
func (UnimplementedHelloworldServer) DeleteHelloworld(context.Context, *DeleteHelloworldRequest) (*DeleteHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHelloworld not implemented")
}
func (UnimplementedHelloworldServer) GetHelloworld(context.Context, *GetHelloworldRequest) (*GetHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHelloworld not implemented")
}
func (UnimplementedHelloworldServer) ListHelloworld(context.Context, *ListHelloworldRequest) (*ListHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHelloworld not implemented")
}
func (UnimplementedHelloworldServer) mustEmbedUnimplementedHelloworldServer() {}
func (UnimplementedHelloworldServer) testEmbeddedByValue()                    {}

// UnsafeHelloworldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloworldServer will
// result in compilation errors.
type UnsafeHelloworldServer interface {
	mustEmbedUnimplementedHelloworldServer()
}

func RegisterHelloworldServer(s grpc.ServiceRegistrar, srv HelloworldServer) {
	// If the following call pancis, it indicates UnimplementedHelloworldServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Helloworld_ServiceDesc, srv)
}

func _Helloworld_CreateHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).CreateHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helloworld_CreateHelloworld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).CreateHelloworld(ctx, req.(*CreateHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_UpdateHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).UpdateHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helloworld_UpdateHelloworld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).UpdateHelloworld(ctx, req.(*UpdateHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_DeleteHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).DeleteHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helloworld_DeleteHelloworld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).DeleteHelloworld(ctx, req.(*DeleteHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_GetHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).GetHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helloworld_GetHelloworld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).GetHelloworld(ctx, req.(*GetHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_ListHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).ListHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helloworld_ListHelloworld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).ListHelloworld(ctx, req.(*ListHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Helloworld_ServiceDesc is the grpc.ServiceDesc for Helloworld service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helloworld_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.helloworld.Helloworld",
	HandlerType: (*HelloworldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHelloworld",
			Handler:    _Helloworld_CreateHelloworld_Handler,
		},
		{
			MethodName: "UpdateHelloworld",
			Handler:    _Helloworld_UpdateHelloworld_Handler,
		},
		{
			MethodName: "DeleteHelloworld",
			Handler:    _Helloworld_DeleteHelloworld_Handler,
		},
		{
			MethodName: "GetHelloworld",
			Handler:    _Helloworld_GetHelloworld_Handler,
		},
		{
			MethodName: "ListHelloworld",
			Handler:    _Helloworld_ListHelloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
