// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: helloworld/helloworld.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHelloworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHelloworldRequest) Reset() {
	*x = CreateHelloworldRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHelloworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHelloworldRequest) ProtoMessage() {}

func (x *CreateHelloworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHelloworldRequest.ProtoReflect.Descriptor instead.
func (*CreateHelloworldRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{0}
}

type CreateHelloworldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHelloworldReply) Reset() {
	*x = CreateHelloworldReply{}
	mi := &file_helloworld_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHelloworldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHelloworldReply) ProtoMessage() {}

func (x *CreateHelloworldReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHelloworldReply.ProtoReflect.Descriptor instead.
func (*CreateHelloworldReply) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{1}
}

type UpdateHelloworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHelloworldRequest) Reset() {
	*x = UpdateHelloworldRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHelloworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHelloworldRequest) ProtoMessage() {}

func (x *UpdateHelloworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHelloworldRequest.ProtoReflect.Descriptor instead.
func (*UpdateHelloworldRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{2}
}

type UpdateHelloworldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHelloworldReply) Reset() {
	*x = UpdateHelloworldReply{}
	mi := &file_helloworld_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHelloworldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHelloworldReply) ProtoMessage() {}

func (x *UpdateHelloworldReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHelloworldReply.ProtoReflect.Descriptor instead.
func (*UpdateHelloworldReply) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{3}
}

type DeleteHelloworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHelloworldRequest) Reset() {
	*x = DeleteHelloworldRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHelloworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloworldRequest) ProtoMessage() {}

func (x *DeleteHelloworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloworldRequest.ProtoReflect.Descriptor instead.
func (*DeleteHelloworldRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{4}
}

type DeleteHelloworldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHelloworldReply) Reset() {
	*x = DeleteHelloworldReply{}
	mi := &file_helloworld_helloworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHelloworldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloworldReply) ProtoMessage() {}

func (x *DeleteHelloworldReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloworldReply.ProtoReflect.Descriptor instead.
func (*DeleteHelloworldReply) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{5}
}

type GetHelloworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelloworldRequest) Reset() {
	*x = GetHelloworldRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelloworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloworldRequest) ProtoMessage() {}

func (x *GetHelloworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloworldRequest.ProtoReflect.Descriptor instead.
func (*GetHelloworldRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{6}
}

type GetHelloworldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelloworldReply) Reset() {
	*x = GetHelloworldReply{}
	mi := &file_helloworld_helloworld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelloworldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloworldReply) ProtoMessage() {}

func (x *GetHelloworldReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloworldReply.ProtoReflect.Descriptor instead.
func (*GetHelloworldReply) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{7}
}

type ListHelloworldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelloworldRequest) Reset() {
	*x = ListHelloworldRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelloworldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloworldRequest) ProtoMessage() {}

func (x *ListHelloworldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloworldRequest.ProtoReflect.Descriptor instead.
func (*ListHelloworldRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{8}
}

type ListHelloworldReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelloworldReply) Reset() {
	*x = ListHelloworldReply{}
	mi := &file_helloworld_helloworld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelloworldReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloworldReply) ProtoMessage() {}

func (x *ListHelloworldReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloworldReply.ProtoReflect.Descriptor instead.
func (*ListHelloworldReply) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{9}
}

var File_helloworld_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/helloworld.proto\x12\x0eapi.helloworld\"\x19\n" +
	"\x17CreateHelloworldRequest\"\x17\n" +
	"\x15CreateHelloworldReply\"\x19\n" +
	"\x17UpdateHelloworldRequest\"\x17\n" +
	"\x15UpdateHelloworldReply\"\x19\n" +
	"\x17DeleteHelloworldRequest\"\x17\n" +
	"\x15DeleteHelloworldReply\"\x16\n" +
	"\x14GetHelloworldRequest\"\x14\n" +
	"\x12GetHelloworldReply\"\x17\n" +
	"\x15ListHelloworldRequest\"\x15\n" +
	"\x13ListHelloworldReply2\xf1\x03\n" +
	"\n" +
	"Helloworld\x12b\n" +
	"\x10CreateHelloworld\x12'.api.helloworld.CreateHelloworldRequest\x1a%.api.helloworld.CreateHelloworldReply\x12b\n" +
	"\x10UpdateHelloworld\x12'.api.helloworld.UpdateHelloworldRequest\x1a%.api.helloworld.UpdateHelloworldReply\x12b\n" +
	"\x10DeleteHelloworld\x12'.api.helloworld.DeleteHelloworldRequest\x1a%.api.helloworld.DeleteHelloworldReply\x12Y\n" +
	"\rGetHelloworld\x12$.api.helloworld.GetHelloworldRequest\x1a\".api.helloworld.GetHelloworldReply\x12\\\n" +
	"\x0eListHelloworld\x12%.api.helloworld.ListHelloworldRequest\x1a#.api.helloworld.ListHelloworldReplyB8\n" +
	"\x0eapi.helloworldP\x01Z$helloworld/api/helloworld;helloworldb\x06proto3"

var (
	file_helloworld_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_helloworld_proto_rawDescData []byte
)

func file_helloworld_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_helloworld_proto_rawDesc), len(file_helloworld_helloworld_proto_rawDesc)))
	})
	return file_helloworld_helloworld_proto_rawDescData
}

var file_helloworld_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_helloworld_helloworld_proto_goTypes = []any{
	(*CreateHelloworldRequest)(nil), // 0: api.helloworld.CreateHelloworldRequest
	(*CreateHelloworldReply)(nil),   // 1: api.helloworld.CreateHelloworldReply
	(*UpdateHelloworldRequest)(nil), // 2: api.helloworld.UpdateHelloworldRequest
	(*UpdateHelloworldReply)(nil),   // 3: api.helloworld.UpdateHelloworldReply
	(*DeleteHelloworldRequest)(nil), // 4: api.helloworld.DeleteHelloworldRequest
	(*DeleteHelloworldReply)(nil),   // 5: api.helloworld.DeleteHelloworldReply
	(*GetHelloworldRequest)(nil),    // 6: api.helloworld.GetHelloworldRequest
	(*GetHelloworldReply)(nil),      // 7: api.helloworld.GetHelloworldReply
	(*ListHelloworldRequest)(nil),   // 8: api.helloworld.ListHelloworldRequest
	(*ListHelloworldReply)(nil),     // 9: api.helloworld.ListHelloworldReply
}
var file_helloworld_helloworld_proto_depIdxs = []int32{
	0, // 0: api.helloworld.Helloworld.CreateHelloworld:input_type -> api.helloworld.CreateHelloworldRequest
	2, // 1: api.helloworld.Helloworld.UpdateHelloworld:input_type -> api.helloworld.UpdateHelloworldRequest
	4, // 2: api.helloworld.Helloworld.DeleteHelloworld:input_type -> api.helloworld.DeleteHelloworldRequest
	6, // 3: api.helloworld.Helloworld.GetHelloworld:input_type -> api.helloworld.GetHelloworldRequest
	8, // 4: api.helloworld.Helloworld.ListHelloworld:input_type -> api.helloworld.ListHelloworldRequest
	1, // 5: api.helloworld.Helloworld.CreateHelloworld:output_type -> api.helloworld.CreateHelloworldReply
	3, // 6: api.helloworld.Helloworld.UpdateHelloworld:output_type -> api.helloworld.UpdateHelloworldReply
	5, // 7: api.helloworld.Helloworld.DeleteHelloworld:output_type -> api.helloworld.DeleteHelloworldReply
	7, // 8: api.helloworld.Helloworld.GetHelloworld:output_type -> api.helloworld.GetHelloworldReply
	9, // 9: api.helloworld.Helloworld.ListHelloworld:output_type -> api.helloworld.ListHelloworldReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_helloworld_proto_init() }
func file_helloworld_helloworld_proto_init() {
	if File_helloworld_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_helloworld_proto_rawDesc), len(file_helloworld_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_helloworld_proto = out.File
	file_helloworld_helloworld_proto_goTypes = nil
	file_helloworld_helloworld_proto_depIdxs = nil
}
