// demo/proto/author/author.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: author/author.proto

// 声明protobuf中的包名

package author

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_author_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_author_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_author_author_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_author_author_proto protoreflect.FileDescriptor

const file_author_author_proto_rawDesc = "" +
	"\n" +
	"\x13author/author.proto\x12\x06author\"\x1a\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\"Z github.com/testProject/pb/authorb\x06proto3"

var (
	file_author_author_proto_rawDescOnce sync.Once
	file_author_author_proto_rawDescData []byte
)

func file_author_author_proto_rawDescGZIP() []byte {
	file_author_author_proto_rawDescOnce.Do(func() {
		file_author_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_author_author_proto_rawDesc), len(file_author_author_proto_rawDesc)))
	})
	return file_author_author_proto_rawDescData
}

var file_author_author_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_author_author_proto_goTypes = []any{
	(*Info)(nil), // 0: author.Info
}
var file_author_author_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_author_author_proto_init() }
func file_author_author_proto_init() {
	if File_author_author_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_author_author_proto_rawDesc), len(file_author_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_author_author_proto_goTypes,
		DependencyIndexes: file_author_author_proto_depIdxs,
		MessageInfos:      file_author_author_proto_msgTypes,
	}.Build()
	File_author_author_proto = out.File
	file_author_author_proto_goTypes = nil
	file_author_author_proto_depIdxs = nil
}
