// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: helloworld/v1/todo.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MassageInfo   string                 `protobuf:"bytes,2,opt,name=massageInfo,proto3" json:"massageInfo,omitempty"`
	States        bool                   `protobuf:"varint,3,opt,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoMessage) Reset() {
	*x = TodoMessage{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoMessage) ProtoMessage() {}

func (x *TodoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoMessage.ProtoReflect.Descriptor instead.
func (*TodoMessage) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *TodoMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoMessage) GetMassageInfo() string {
	if x != nil {
		return x.MassageInfo
	}
	return ""
}

func (x *TodoMessage) GetStates() bool {
	if x != nil {
		return x.States
	}
	return false
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MassageInfo   string                 `protobuf:"bytes,1,opt,name=massageInfo,proto3" json:"massageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetMassageInfo() string {
	if x != nil {
		return x.MassageInfo
	}
	return ""
}

type CreateTodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *TodoMessage           `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoReply) Reset() {
	*x = CreateTodoReply{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoReply) ProtoMessage() {}

func (x *CreateTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoReply.ProtoReflect.Descriptor instead.
func (*CreateTodoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoReply) GetTodo() *TodoMessage {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MassageInfo   string                 `protobuf:"bytes,2,opt,name=massageInfo,proto3" json:"massageInfo,omitempty"`
	States        bool                   `protobuf:"varint,3,opt,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTodoRequest) GetMassageInfo() string {
	if x != nil {
		return x.MassageInfo
	}
	return ""
}

func (x *UpdateTodoRequest) GetStates() bool {
	if x != nil {
		return x.States
	}
	return false
}

type UpdateTodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoReply) Reset() {
	*x = UpdateTodoReply{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoReply) ProtoMessage() {}

func (x *UpdateTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoReply.ProtoReflect.Descriptor instead.
func (*UpdateTodoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{4}
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoReply) Reset() {
	*x = DeleteTodoReply{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoReply) ProtoMessage() {}

func (x *DeleteTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoReply.ProtoReflect.Descriptor instead.
func (*DeleteTodoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{6}
}

type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *GetTodoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *TodoMessage           `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoReply) Reset() {
	*x = GetTodoReply{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoReply) ProtoMessage() {}

func (x *GetTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoReply.ProtoReflect.Descriptor instead.
func (*GetTodoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *GetTodoReply) GetTodo() *TodoMessage {
	if x != nil {
		return x.Todo
	}
	return nil
}

type ListTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodoRequest) Reset() {
	*x = ListTodoRequest{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodoRequest) ProtoMessage() {}

func (x *ListTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodoRequest.ProtoReflect.Descriptor instead.
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{9}
}

type ListTodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TodoMessage         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodoReply) Reset() {
	*x = ListTodoReply{}
	mi := &file_helloworld_v1_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodoReply) ProtoMessage() {}

func (x *ListTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodoReply.ProtoReflect.Descriptor instead.
func (*ListTodoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_todo_proto_rawDescGZIP(), []int{10}
}

func (x *ListTodoReply) GetData() []*TodoMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_helloworld_v1_todo_proto protoreflect.FileDescriptor

const file_helloworld_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/todo.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\vTodoMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vmassageInfo\x18\x02 \x01(\tR\vmassageInfo\x12\x16\n" +
	"\x06states\x18\x03 \x01(\bR\x06states\"5\n" +
	"\x11CreateTodoRequest\x12 \n" +
	"\vmassageInfo\x18\x01 \x01(\tR\vmassageInfo\"E\n" +
	"\x0fCreateTodoReply\x122\n" +
	"\x04todo\x18\x01 \x01(\v2\x1e.api.helloworld.v1.TodoMessageR\x04todo\"]\n" +
	"\x11UpdateTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vmassageInfo\x18\x02 \x01(\tR\vmassageInfo\x12\x16\n" +
	"\x06states\x18\x03 \x01(\bR\x06states\"\x11\n" +
	"\x0fUpdateTodoReply\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteTodoReply\" \n" +
	"\x0eGetTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\fGetTodoReply\x122\n" +
	"\x04todo\x18\x01 \x01(\v2\x1e.api.helloworld.v1.TodoMessageR\x04todo\"\x11\n" +
	"\x0fListTodoRequest\"C\n" +
	"\rListTodoReply\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.api.helloworld.v1.TodoMessageR\x04data2\xa7\x04\n" +
	"\x04Todo\x12k\n" +
	"\n" +
	"CreateTodo\x12$.api.helloworld.v1.CreateTodoRequest\x1a\".api.helloworld.v1.CreateTodoReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/todo\x12p\n" +
	"\n" +
	"UpdateTodo\x12$.api.helloworld.v1.UpdateTodoRequest\x1a\".api.helloworld.v1.UpdateTodoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/todo/{id}\x12p\n" +
	"\n" +
	"DeleteTodo\x12$.api.helloworld.v1.DeleteTodoRequest\x1a\".api.helloworld.v1.DeleteTodoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01**\r/v1/todo/{id}\x12g\n" +
	"\aGetTodo\x12!.api.helloworld.v1.GetTodoRequest\x1a\x1f.api.helloworld.v1.GetTodoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x12\r/v1/todo/{id}\x12e\n" +
	"\bListTodo\x12\".api.helloworld.v1.ListTodoRequest\x1a .api.helloworld.v1.ListTodoReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\x12\b/v1/todoB6\n" +
	"\x11api.helloworld.v1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_todo_proto_rawDescOnce sync.Once
	file_helloworld_v1_todo_proto_rawDescData []byte
)

func file_helloworld_v1_todo_proto_rawDescGZIP() []byte {
	file_helloworld_v1_todo_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_todo_proto_rawDesc), len(file_helloworld_v1_todo_proto_rawDesc)))
	})
	return file_helloworld_v1_todo_proto_rawDescData
}

var file_helloworld_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_helloworld_v1_todo_proto_goTypes = []any{
	(*TodoMessage)(nil),       // 0: api.helloworld.v1.TodoMessage
	(*CreateTodoRequest)(nil), // 1: api.helloworld.v1.CreateTodoRequest
	(*CreateTodoReply)(nil),   // 2: api.helloworld.v1.CreateTodoReply
	(*UpdateTodoRequest)(nil), // 3: api.helloworld.v1.UpdateTodoRequest
	(*UpdateTodoReply)(nil),   // 4: api.helloworld.v1.UpdateTodoReply
	(*DeleteTodoRequest)(nil), // 5: api.helloworld.v1.DeleteTodoRequest
	(*DeleteTodoReply)(nil),   // 6: api.helloworld.v1.DeleteTodoReply
	(*GetTodoRequest)(nil),    // 7: api.helloworld.v1.GetTodoRequest
	(*GetTodoReply)(nil),      // 8: api.helloworld.v1.GetTodoReply
	(*ListTodoRequest)(nil),   // 9: api.helloworld.v1.ListTodoRequest
	(*ListTodoReply)(nil),     // 10: api.helloworld.v1.ListTodoReply
}
var file_helloworld_v1_todo_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.v1.CreateTodoReply.todo:type_name -> api.helloworld.v1.TodoMessage
	0,  // 1: api.helloworld.v1.GetTodoReply.todo:type_name -> api.helloworld.v1.TodoMessage
	0,  // 2: api.helloworld.v1.ListTodoReply.data:type_name -> api.helloworld.v1.TodoMessage
	1,  // 3: api.helloworld.v1.Todo.CreateTodo:input_type -> api.helloworld.v1.CreateTodoRequest
	3,  // 4: api.helloworld.v1.Todo.UpdateTodo:input_type -> api.helloworld.v1.UpdateTodoRequest
	5,  // 5: api.helloworld.v1.Todo.DeleteTodo:input_type -> api.helloworld.v1.DeleteTodoRequest
	7,  // 6: api.helloworld.v1.Todo.GetTodo:input_type -> api.helloworld.v1.GetTodoRequest
	9,  // 7: api.helloworld.v1.Todo.ListTodo:input_type -> api.helloworld.v1.ListTodoRequest
	2,  // 8: api.helloworld.v1.Todo.CreateTodo:output_type -> api.helloworld.v1.CreateTodoReply
	4,  // 9: api.helloworld.v1.Todo.UpdateTodo:output_type -> api.helloworld.v1.UpdateTodoReply
	6,  // 10: api.helloworld.v1.Todo.DeleteTodo:output_type -> api.helloworld.v1.DeleteTodoReply
	8,  // 11: api.helloworld.v1.Todo.GetTodo:output_type -> api.helloworld.v1.GetTodoReply
	10, // 12: api.helloworld.v1.Todo.ListTodo:output_type -> api.helloworld.v1.ListTodoReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_helloworld_v1_todo_proto_init() }
func file_helloworld_v1_todo_proto_init() {
	if File_helloworld_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_todo_proto_rawDesc), len(file_helloworld_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_todo_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_todo_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_todo_proto_msgTypes,
	}.Build()
	File_helloworld_v1_todo_proto = out.File
	file_helloworld_v1_todo_proto_goTypes = nil
	file_helloworld_v1_todo_proto_depIdxs = nil
}
