// demo/proto/book/book.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: book/book.proto

// 声明protobuf中的包名

package book

import (
	author "github.com/testProject/pb/author"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         *Price                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	AuthorInfo    *author.Info           `protobuf:"bytes,3,opt,name=authorInfo,proto3" json:"authorInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Book) GetAuthorInfo() *author.Info {
	if x != nil {
		return x.AuthorInfo
	}
	return nil
}

type BookCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookCreateResponse) Reset() {
	*x = BookCreateResponse{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreateResponse) ProtoMessage() {}

func (x *BookCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreateResponse.ProtoReflect.Descriptor instead.
func (*BookCreateResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookCreateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\x1a\x10book/price.proto\x1a\x13author/author.proto\"y\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\x05price\x18\x02 \x01(\v2\v.book.PriceR\x05price\x12,\n" +
	"\n" +
	"authorInfo\x18\x03 \x01(\v2\f.author.InfoR\n" +
	"authorInfoJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\",\n" +
	"\x12BookCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2?\n" +
	"\vBookService\x120\n" +
	"\x06Create\x12\n" +
	".book.Book\x1a\x18.book.BookCreateResponse\"\x00B Z\x1egithub.com/testProject/pb/bookb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_book_book_proto_goTypes = []any{
	(*Book)(nil),               // 0: book.Book
	(*BookCreateResponse)(nil), // 1: book.BookCreateResponse
	(*Price)(nil),              // 2: book.Price
	(*author.Info)(nil),        // 3: author.Info
}
var file_book_book_proto_depIdxs = []int32{
	2, // 0: book.Book.price:type_name -> book.Price
	3, // 1: book.Book.authorInfo:type_name -> author.Info
	0, // 2: book.BookService.Create:input_type -> book.Book
	1, // 3: book.BookService.Create:output_type -> book.BookCreateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	file_book_price_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
