// demo/proto/book/book.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: book/book.proto

// 声明protobuf中的包名

package book

import (
	author "github.com/testProject/pb/author"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         *Price                  `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	AuthorInfo    *author.Info            `protobuf:"bytes,3,opt,name=authorInfo,proto3" json:"authorInfo,omitempty"`
	Idx           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Book) GetAuthorInfo() *author.Info {
	if x != nil {
		return x.AuthorInfo
	}
	return nil
}

func (x *Book) GetIdx() *wrapperspb.StringValue {
	if x != nil {
		return x.Idx
	}
	return nil
}

type BookCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookCreateResponse) Reset() {
	*x = BookCreateResponse{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreateResponse) ProtoMessage() {}

func (x *BookCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreateResponse.ProtoReflect.Descriptor instead.
func (*BookCreateResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookCreateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BookUpdateMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookUpdateMsg) Reset() {
	*x = BookUpdateMsg{}
	mi := &file_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookUpdateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdateMsg) ProtoMessage() {}

func (x *BookUpdateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdateMsg.ProtoReflect.Descriptor instead.
func (*BookUpdateMsg) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *BookUpdateMsg) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *BookUpdateMsg) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type BookUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookUpdateResponse) Reset() {
	*x = BookUpdateResponse{}
	mi := &file_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdateResponse) ProtoMessage() {}

func (x *BookUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdateResponse.ProtoReflect.Descriptor instead.
func (*BookUpdateResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *BookUpdateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type HotBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotBooksRequest) Reset() {
	*x = HotBooksRequest{}
	mi := &file_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotBooksRequest) ProtoMessage() {}

func (x *HotBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotBooksRequest.ProtoReflect.Descriptor instead.
func (*HotBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *HotBooksRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type HotBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookName      string                 `protobuf:"bytes,1,opt,name=bookName,proto3" json:"bookName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotBooksResponse) Reset() {
	*x = HotBooksResponse{}
	mi := &file_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotBooksResponse) ProtoMessage() {}

func (x *HotBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotBooksResponse.ProtoReflect.Descriptor instead.
func (*HotBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *HotBooksResponse) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\x1a\x10book/price.proto\x1a\x13author/author.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\"\xa9\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\x05price\x18\x02 \x01(\v2\v.book.PriceR\x05price\x12,\n" +
	"\n" +
	"authorInfo\x18\x03 \x01(\v2\f.author.InfoR\n" +
	"authorInfo\x12.\n" +
	"\x03idx\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x03idxJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\",\n" +
	"\x12BookCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"l\n" +
	"\rBookUpdateMsg\x12\x1e\n" +
	"\x04book\x18\x01 \x01(\v2\n" +
	".book.BookR\x04book\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\",\n" +
	"\x12BookUpdateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"+\n" +
	"\x0fHotBooksRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\".\n" +
	"\x10HotBooksResponse\x12\x1a\n" +
	"\bbookName\x18\x01 \x01(\tR\bbookName2\xbc\x01\n" +
	"\vBookService\x120\n" +
	"\x06Create\x12\n" +
	".book.Book\x1a\x18.book.BookCreateResponse\"\x00\x129\n" +
	"\x06Update\x12\x13.book.BookUpdateMsg\x1a\x18.book.BookUpdateResponse\"\x00\x12@\n" +
	"\vGetHotBooks\x12\x15.book.HotBooksRequest\x1a\x16.book.HotBooksResponse(\x010\x01B Z\x1egithub.com/testProject/pb/bookb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_book_book_proto_goTypes = []any{
	(*Book)(nil),                   // 0: book.Book
	(*BookCreateResponse)(nil),     // 1: book.BookCreateResponse
	(*BookUpdateMsg)(nil),          // 2: book.BookUpdateMsg
	(*BookUpdateResponse)(nil),     // 3: book.BookUpdateResponse
	(*HotBooksRequest)(nil),        // 4: book.HotBooksRequest
	(*HotBooksResponse)(nil),       // 5: book.HotBooksResponse
	(*Price)(nil),                  // 6: book.Price
	(*author.Info)(nil),            // 7: author.Info
	(*wrapperspb.StringValue)(nil), // 8: google.protobuf.StringValue
	(*fieldmaskpb.FieldMask)(nil),  // 9: google.protobuf.FieldMask
}
var file_book_book_proto_depIdxs = []int32{
	6, // 0: book.Book.price:type_name -> book.Price
	7, // 1: book.Book.authorInfo:type_name -> author.Info
	8, // 2: book.Book.idx:type_name -> google.protobuf.StringValue
	0, // 3: book.BookUpdateMsg.book:type_name -> book.Book
	9, // 4: book.BookUpdateMsg.update_mask:type_name -> google.protobuf.FieldMask
	0, // 5: book.BookService.Create:input_type -> book.Book
	2, // 6: book.BookService.Update:input_type -> book.BookUpdateMsg
	4, // 7: book.BookService.GetHotBooks:input_type -> book.HotBooksRequest
	1, // 8: book.BookService.Create:output_type -> book.BookCreateResponse
	3, // 9: book.BookService.Update:output_type -> book.BookUpdateResponse
	5, // 10: book.BookService.GetHotBooks:output_type -> book.HotBooksResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	file_book_price_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
