// proto/book/price.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: book/price.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketPrice   int64                  `protobuf:"varint,1,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"` // 建议使用下划线的命名方式
	SalePrice     int64                  `protobuf:"varint,2,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_book_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_book_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_book_price_proto_rawDescGZIP(), []int{0}
}

func (x *Price) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *Price) GetSalePrice() int64 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

var File_book_price_proto protoreflect.FileDescriptor

const file_book_price_proto_rawDesc = "" +
	"\n" +
	"\x10book/price.proto\x12\x04book\"I\n" +
	"\x05Price\x12!\n" +
	"\fmarket_price\x18\x01 \x01(\x03R\vmarketPrice\x12\x1d\n" +
	"\n" +
	"sale_price\x18\x02 \x01(\x03R\tsalePriceB Z\x1egithub.com/testProject/pb/bookb\x06proto3"

var (
	file_book_price_proto_rawDescOnce sync.Once
	file_book_price_proto_rawDescData []byte
)

func file_book_price_proto_rawDescGZIP() []byte {
	file_book_price_proto_rawDescOnce.Do(func() {
		file_book_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_price_proto_rawDesc), len(file_book_price_proto_rawDesc)))
	})
	return file_book_price_proto_rawDescData
}

var file_book_price_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_price_proto_goTypes = []any{
	(*Price)(nil), // 0: book.Price
}
var file_book_price_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_price_proto_init() }
func file_book_price_proto_init() {
	if File_book_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_price_proto_rawDesc), len(file_book_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_book_price_proto_goTypes,
		DependencyIndexes: file_book_price_proto_depIdxs,
		MessageInfos:      file_book_price_proto_msgTypes,
	}.Build()
	File_book_price_proto = out.File
	file_book_price_proto_goTypes = nil
	file_book_price_proto_depIdxs = nil
}
